Draft: Add option to specify storage site and optionally specify the output directory.
cerminar/submission pull request #4
Opened 2024-07-31 17:06 UTC by arsahasransu

Code maintains backward compatibility. 

- Add option to specify the storage site using `storage_site` in yaml configuration file.
- Optionally specify the output directory in crab jobs.
 -  If you specify the output directory starting with "/eos/cms", the modification used earlier is still valid to allow backward compatibility. 
 - Throws a warning if you specify the option which is not "/eos/cms" to make the user aware of potential trouble. 
 - Throws an error if you specify condor and do not specify the output directory. 
- Some small deletions of unused code.

2024-08-01 08:39 UTC, cerminar requested changes
Thanks, @arsahasransu! It looks good except for the changes to the `sumbit_INFP_131X.yaml` file. Please don't comment out the samples that you don't use; just add new ones if needed. The `task` list, anyway, selects which one to run. 
Also, please don't change the default storage site in there...maybe add yours commented out.

2024-08-01 11:16 UTC, arsahasransu commented
> Thanks, @arsahasransu! It looks good except for the changes to the `sumbit_INFP_131X.yaml` file. Please don't comment out the samples that you don't use; just add new ones if needed. The `task` list, anyway, selects which one to run. Also, please don't change the default storage site in there...maybe add yours commented out.

Changed

2024-08-01 11:20 UTC, arsahasransu reviewed
Comment resolved.

2024-08-02 09:31 UTC, cerminar approved these changes

2024-08-02 09:31 UTC, merged